---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredump
  namespace: kube-system
secrets:
- name: coredump-secret-token
---
apiVersion: v1
kind: Secret
metadata:
  name: coredump-secret-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: coredump
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredump-clusterrole
  namespace: kube-system
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - pods
  verbs: ["get", "list"]
- nonResourceURLs: ["/pods"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredump-clusterrole-binding
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: coredump-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: coredump
  namespace: kube-system
